# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    #runs-on: ubuntu-20.04
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-20.04', 'windows-2019' ]
    name: Java (${{ matrix.os }}) sample
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Compile java files with JDK 8
      run: |
        javac -version
        pwd
        mkdir out
        cd out
        javac -source 1.4 -Xmaxerrs 1 -Xlint:-options ../src/*.java
        jar cvfe BibleReader.jar Main -C ../src .
    - name: Set up JDK 17 (GraalVM)
      uses: actions/setup-java@v4
      with:
        java-version: '17.0.12'
        distribution: 'graalvm'
    - name: Create native binary
      run: |
        javac -version
        cd out
        pwd
        native-image -jar BibleReader.jar -H:IncludeResources=".*txt$" -H:-CheckToolchain
#    - name: Build with Ant
#      run: ant -noinput -buildfile build.xml
